import requests

def fix_latex_with_ollama(latex_text: str, model_name: str = "gemma", api_url: str = "http://chatbot.tail36da8e.ts.net:11434") -> str:
    """
    Gửi mã LaTeX gốc cho mô hình LLM thông qua Ollama để:
    1. Sửa các lỗi cú pháp LaTeX (đóng/mở ngoặc, thiếu $, \end mồ côi).
    2. Cân bằng các môi trường toán học.
    3. Nhận diện và khôi phục các công thức vật lý (Dirac, Feynman) bị OCR ảo giác.
    """
    prompt = (
        "You are an expert in High Energy Physics and LaTeX. Review the following LaTeX code generated by an OCR engine. "
        "Your tasks:\n"
        "1. Fix any syntax errors (e.g., missing backslashes like begin{aligned} -> \\begin{aligned}, unclosed environments, mismatched brackets \\left( and \\right}, missing $ signs).\n"
        "2. Ensure environments like \\begin{aligned} are properly placed inside math mode (e.g., inside \\begin{equation} or $$).\n"
        "3. Correct OCR hallucinations in physics/math equations (e.g., Dirac matrices, Feynman rules, momentum slash \\not\\!p, subscripts) based on context.\n"
        "4. Do NOT remove any text or document structure (like \\documentclass or \\begin{document}). ONLY output the corrected LaTeX code without any markdown formatting or explanations.\n\n"
        "LaTeX Code:\n"
        f"{latex_text}"
    )

    payload = {
        "model": model_name,
        "prompt": prompt,
        "stream": False
    }

    try:
        response = requests.post(f"{api_url}/api/generate", json=payload, timeout=180)
        response.raise_for_status()
        result = response.json()
        corrected_text = result.get("response", "")
        
        # Clean up markdown code blocks if the LLM wrapped it
        corrected_text = corrected_text.strip()
        if corrected_text.startswith("```"):
            lines = corrected_text.splitlines()
            if lines[0].startswith("```"):
                lines = lines[1:]
            if lines and lines[-1].startswith("```"):
                lines = lines[:-1]
            corrected_text = "\n".join(lines).strip()
            
        return corrected_text
    except Exception as e:
        raise Exception(f"Lỗi khi kết nối Ollama API ({api_url}): {e}")
